#ifndef CORE_COMMANDBYTES_H
#define CORE_COMMANDBYTES_H

#define CMB_DEVICE_IDENTIFICATION 0xE0
#define CMB_I2C 0xE1
#define RC_SWITCH 0xE4
#define CMB_DS18B20 0xE5
#define CMB_IR 0xE6
#define CMB_COMMON_INTERRUPT 0xE7


#endif //CORE_COMMANDBYTES_H
