language: java
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

script:
  - cd core && gradle check
  - cd ../java && gradle check
#  - cd ../avr/seed_project && cmake . && make 
